### ISSUE TITLE
Add HTTPS

### ISSUE THREAD

**Issue by CrowdHailer** [Nagasaki45/watercooler-2#2]
Hi,

One I have just added the required set up to have a secure HTTPS endpoint. Have no idea how to do that with cowboy so would be curious to see what that looked like here.

Also I have changed the example structure to match what I did in the talk a bit more.

- Have a `/water_cooler/application.ex` file which is a convention in the latest mix generator
- Have a `water_cooler/www.ex` file which was something I started doing before the application file was added so am now completely unsure if it is necessary or not.

**Comment by Nagasaki45** [comment]
Refactoring the application code out of the web code: Done 6b118f5648bae249728281d3b63d4ae3d613ab93.
Add SSL support: Done e8ff71fda73e6a9dc148d18dc7f5dbcd8e987284.

**Comment by CrowdHailer** [comment]
:+1:
