### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by CrowdHailer** [Nagasaki45/watercooler-2#3]
Also done, are tests

https://github.com/CrowdHailer/Tokumei/blob/master/water_cooler/test/watercooler/www_test.exs

**Comment by CrowdHailer** [comment]
Do you have any more ideas for checking testing the chunked responses? Might be an interesting thing to discuss in the forum

**Comment by Nagasaki45** [comment]
I wrote my findings in the forum https://elixirforum.com/t/testing-chunked-responses-from-a-phoenix-endpoint-using-plug-test-or-phoenix-conntest/3471/2?u=nagasaki45. We can continue the discussion there, as it might be beneficial for others.
